### ISSUE TITLE
Install additional tooling

### ISSUE THREAD

**Issue by trevorbryant** [rfhs/rfctf-support#5]
Please add the following tools the kali (potentially all) environments.

Happy for feedback.

* vim
* mlocate
* man
* sudo
* pciutils (duplicate https://github.com/rfhs/wctf-support/issues/2)
* hashcat
* wpasupplicant
* less
* bash-completion
* hashcat (duplicate https://github.com/rfhs/wctf-support/issues/3)

**Comment by ZeroChaos-** [comment]
[] vim
[] mlocate
[] man
~~[] sudo~~ the containers all run as root, sudo serves no purpose
[] pciutils (duplicate #2)
[] wpasupplicant
[] less
[] bash-completion
[] hashcat (duplicate #3)

**Comment by ZeroChaos-** [comment]
https://github.com/rfhs/rfctf-container
