### ISSUE TITLE
WEP Challenge Scoring Not Checking Against Team

### ISSUE THREAD

**Issue by scootmcgavin** [rfhs/rfctf-support#9]
In previous RFCTF, a player could submit all three flags (asii, upper, and lower) for triple points. As of DC29, a fix was implemented that prevents an individual user from doing so. However, the submissions are only tracked per user and not against the team account. Meaning a team of atleast three players can still submit all WEP flags.

While not a big deal in past since individuals could submit all three, the current fix disadvantages teams of 1 and 2 who may be unaware of bug.

**Comment by ZeroChaos-** [comment]
this has been fixed, thanks for your report.

team scores have been adjusted automatically to fix the improper scoring
